TRUNCATE public.disease_library RESTART IDENTITY;
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Fungal infection', 'fungal-infection', 'Fungal infection is a common skin condition caused by fungi.', ARRAY[]::text[], ARRAY['bath twice', 'use detol or neem in bathing water', 'keep infected area dry']::text[], ARRAY['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']::text[], ARRAY['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']::text[], ARRAY['Avoid sugary foods', 'Consume probiotics', 'Increase intake of garlic', 'Include yogurt in diet', 'Limit processed foods', 'Stay hydrated', 'Consume green tea', 'Eat foods rich in zinc', 'Include turmeric in diet', 'Eat fruits and vegetables']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Allergy', 'allergy', 'Allergy is an immune system reaction to a substance in the environment.', ARRAY[]::text[], ARRAY['apply calamine', 'cover area with bandage']::text[], ARRAY['Antihistamines', 'Decongestants', 'Epinephrine', 'Corticosteroids', 'Immunotherapy']::text[], ARRAY['Elimination Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']::text[], ARRAY['Avoid allergenic foods', 'Consume anti-inflammatory foods', 'Include omega-3 fatty acids', 'Stay hydrated', 'Eat foods rich in vitamin C', 'Include quercetin-rich foods', 'Consume local honey', 'Limit processed foods', 'Include ginger in diet', 'Avoid artificial additives']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('GERD', 'gerd', 'GERD (Gastroesophageal Reflux Disease) is a digestive disorder that affects the lower esophageal sphincter.', ARRAY[]::text[], ARRAY['avoid fatty spicy food', 'avoid lying down after eating', 'maintain healthy weight']::text[], ARRAY['Proton Pump Inhibitors (PPIs)', 'H2 Blockers', 'Antacids', 'Prokinetics', 'Antibiotics']::text[], ARRAY['Low-Acid Diet', 'Fiber-rich foods', 'Ginger', 'Licorice', 'Aloe vera juice']::text[], ARRAY['Consume smaller meals', 'Avoid trigger foods (spicy, fatty)', 'Eat high-fiber foods', 'Limit caffeine and alcohol', 'Chew food thoroughly', 'Avoid late-night eating', 'Consume non-citrus fruits', 'Include lean proteins', 'Stay hydrated', 'Avoid carbonated beverages']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Chronic cholestasis', 'chronic-cholestasis', 'Chronic cholestasis is a condition where bile flow from the liver is reduced for a prolonged period.', ARRAY[]::text[], ARRAY['cold baths', 'anti itch medicine', 'consult doctor']::text[], ARRAY['Ursodeoxycholic acid', 'Cholestyramine', 'Methotrexate', 'Corticosteroids', 'Liver transplant']::text[], ARRAY['Low-Fat Diet', 'High-Fiber Diet', 'Lean proteins', 'Whole grains', 'Fresh fruits and vegetables']::text[], ARRAY['Consume a low-fat diet', 'Eat high-fiber foods', 'Include healthy fats', 'Limit alcohol consumption', 'Stay hydrated', 'Consume antioxidant-rich foods', 'Include omega-3 fatty acids', 'Include lean proteins', 'Limit processed foods', 'Avoid fried foods']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Drug Reaction', 'drug-reaction', 'Drug Reaction occurs when the body reacts adversely to a medication.', ARRAY[]::text[], ARRAY['stop irritation', 'consult nearest hospital', 'stop taking drug']::text[], ARRAY['Antihistamines', 'Epinephrine', 'Corticosteroids', 'Antibiotics', 'Antifungal Cream']::text[], ARRAY['Antihistamine Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']::text[], ARRAY['Discontinue offending medication', 'Stay hydrated', 'Include anti-inflammatory foods', 'Consume antioxidants', 'Avoid trigger foods', 'Include omega-3 fatty acids', 'Limit caffeine and alcohol', 'Stay hydrated', 'Eat a balanced diet', 'Consult a healthcare professional']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Peptic ulcer disease', 'peptic-ulcer-disease', 'Peptic ulcer disease involves sores that develop on the inner lining of the stomach and small intestine.', ARRAY[]::text[], ARRAY[]::text[], ARRAY['Antibiotics', 'Proton Pump Inhibitors (PPIs)', 'H2 Blockers', 'Antacids', 'Cytoprotective agents']::text[], ARRAY['Low-Acid Diet', 'Fiber-rich foods', 'Ginger', 'Licorice', 'Aloe vera juice']::text[], ARRAY['Consume smaller, more frequent meals', 'Avoid trigger foods (spicy, acidic)', 'Include high-fiber foods', 'Limit caffeine and alcohol', 'Stay hydrated', 'Consume probiotics', 'Include lean proteins', 'Include antioxidant-rich foods', 'Limit processed foods', 'Avoid smoking and alcohol']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('AIDS', 'aids', 'AIDS (Acquired Immunodeficiency Syndrome) is a disease caused by HIV that weakens the immune system.', ARRAY[]::text[], ARRAY['avoid open cuts', 'wear ppe if possible', 'consult doctor']::text[], ARRAY['Antiretroviral drugs', 'Protease inhibitors', 'Integrase inhibitors', 'Entry inhibitors', 'Fusion inhibitors']::text[], ARRAY['Balanced Diet', 'Protein-rich foods', 'Fruits and vegetables', 'Whole grains', 'Healthy fats']::text[], ARRAY['Follow a balanced and nutritious diet', 'Include lean proteins', 'Consume nutrient-rich foods', 'Stay hydrated', 'Include healthy fats', 'Avoid raw or undercooked foods', 'Limit sugary foods and beverages', 'Consume immune-boosting foods', 'Take prescribed supplements', 'Consult a healthcare professional']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Diabetes', 'diabetes', 'Diabetes is a chronic condition that affects how the body processes blood sugar.', ARRAY[]::text[], ARRAY['have balanced diet', 'exercise', 'consult doctor']::text[], ARRAY['Insulin', 'Metformin', 'Sulfonylureas', 'DPP-4 inhibitors', 'GLP-1 receptor agonists']::text[], ARRAY['Low-Glycemic Diet', 'Fiber-rich foods', 'Lean proteins', 'Healthy fats', 'Low-fat dairy']::text[], ARRAY['Monitor carbohydrate intake', 'Eat balanced meals', 'Include lean proteins', 'Consume high-fiber foods', 'Stay hydrated', 'Limit sugary foods and beverages', 'Include healthy fats', 'Monitor blood sugar levels', 'Consult a registered dietitian', 'Take prescribed medications as directed']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Gastroenteritis', 'gastroenteritis', 'Gastroenteritis is an inflammation of the stomach and intestines, typically caused by a virus or bacteria.', ARRAY[]::text[], ARRAY['stop eating solid food for while', 'try taking small sips of water', 'rest']::text[], ARRAY['Antibiotics', 'Antiemetic drugs', 'Antidiarrheal drugs', 'IV fluids', 'Probiotics']::text[], ARRAY['Bland Diet', 'Bananas', 'Rice', 'Applesauce', 'Toast']::text[], ARRAY['Stay hydrated', 'Consume clear fluids', 'Follow the BRAT diet (bananas, rice, applesauce, toast)', 'Include bland foods', 'Avoid fatty and greasy foods', 'Limit caffeine and alcohol', 'Avoid spicy foods', 'Consult a healthcare professional', 'Gradually reintroduce solid foods', 'Avoid dairy products']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Bronchial Asthma', 'bronchial-asthma', 'Bronchial Asthma is a respiratory condition characterized by inflammation of the airways.', ARRAY[]::text[], ARRAY['switch to loose cloothing', 'take deep breaths', 'get away from trigger']::text[], ARRAY['Bronchodilators', 'Inhaled corticosteroids', 'Leukotriene modifiers', 'Mast cell stabilizers', 'Anticholinergics']::text[], ARRAY['Anti-Inflammatory Diet', 'Omega-3-rich foods', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']::text[], ARRAY['Include anti-inflammatory foods', 'Consume omega-3 fatty acids', 'Limit sodium intake', 'Stay hydrated', 'Include antioxidant-rich foods', 'Avoid sulfite-containing foods', 'Limit processed foods', 'Consume magnesium-rich foods', 'Consult a healthcare professional', 'Avoid trigger foods']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hypertension', 'hypertension', 'Hypertension, or high blood pressure, is a common cardiovascular condition.', ARRAY[]::text[], ARRAY['meditation', 'salt baths', 'reduce stress']::text[], ARRAY['Antihypertensive medications', 'Diuretics', 'Beta-blockers', 'ACE inhibitors', 'Calcium channel blockers']::text[], ARRAY['DASH Diet', 'Low-sodium foods', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']::text[], ARRAY['Follow the DASH diet (Dietary Approaches to Stop Hypertension)', 'Limit sodium intake', 'Include potassium-rich foods', 'Stay hydrated', 'Consume calcium-rich foods', 'Limit alcohol consumption', 'Include magnesium-rich foods', 'Consume omega-3 fatty acids', 'Limit processed foods', 'Consult a healthcare professional']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Migraine', 'migraine', 'Migraine is a type of headache that often involves severe pain and sensitivity to light and sound.', ARRAY[]::text[], ARRAY['meditation', 'reduce stress', 'use poloroid glasses in sun']::text[], ARRAY['Analgesics', 'Triptans', 'Ergotamine derivatives', 'Preventive medications', 'Biofeedback']::text[], ARRAY['Migraine Diet', 'Low-Tyramine Diet', 'Caffeine withdrawal', 'Hydration', 'Magnesium-rich foods']::text[], ARRAY['Identify and avoid trigger foods', 'Stay hydrated', 'Include magnesium-rich foods', 'Consume omega-3 fatty acids', 'Limit caffeine and alcohol', 'Consume riboflavin-rich foods', 'Limit processed foods', 'Maintain regular meal times', 'Consult a healthcare professional', 'Manage stress']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Cervical spondylosis', 'cervical-spondylosis', 'Cervical spondylosis is a degenerative condition of the cervical spine.', ARRAY[]::text[], ARRAY['use heating pad or cold pack', 'exercise', 'take otc pain reliver']::text[], ARRAY['Pain relievers', 'Muscle relaxants', 'Physical therapy', 'Neck braces', 'Corticosteroids']::text[], ARRAY['Arthritis Diet', 'Anti-Inflammatory Diet', 'Omega-3-rich foods', 'Fruits and vegetables', 'Whole grains']::text[], ARRAY['Include anti-inflammatory foods', 'Consume omega-3 fatty acids', 'Include vitamin D-rich foods', 'Stay hydrated', 'Consume antioxidant-rich foods', 'Limit processed foods', 'Include lean proteins', 'Practice good posture', 'Consult a healthcare professional', 'Engage in regular exercise']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Paralysis (brain hemorrhage)', 'paralysis-brain-hemorrhage', 'Paralysis (brain hemorrhage) refers to the loss of muscle function due to bleeding in the brain.', ARRAY[]::text[], ARRAY['massage', 'eat healthy', 'exercise']::text[], ARRAY['Blood thinners', 'Clot-dissolving medications', 'Anticonvulsants', 'Physical therapy', 'Occupational therapy']::text[], ARRAY['Heart-Healthy Diet', 'Low-sodium foods', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']::text[], ARRAY['Follow a balanced and nutritious diet', 'Include lean proteins', 'Consume nutrient-rich foods', 'Stay hydrated', 'Include healthy fats', 'Limit sugary foods and beverages', 'Include antioxidants', 'Consume foods rich in vitamin K', 'Consult a healthcare professional', 'Manage stress']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Jaundice', 'jaundice', 'Jaundice is a yellow discoloration of the skin and eyes, often indicating liver problems.', ARRAY[]::text[], ARRAY['drink plenty of water', 'consume milk thistle', 'eat fruits and high fiberous food']::text[], ARRAY['IV fluids', 'Blood transfusions', 'Liver transplant', 'Medications for itching', 'Antiviral medications']::text[], ARRAY['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']::text[], ARRAY['Stay hydrated', 'Consume nutrient-rich foods', 'Include protein-rich foods', 'Consume easily digestible foods', 'Limit fatty foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Malaria', 'malaria', 'Malaria is a mosquito-borne infectious disease affecting humans and other animals.', ARRAY[]::text[], ARRAY['Consult nearest hospital', 'avoid oily food', 'avoid non veg food']::text[], ARRAY['Antimalarial drugs', 'Antipyretics', 'Antiemetic drugs', 'IV fluids', 'Blood transfusions']::text[], ARRAY['Malaria Diet', 'Hydration', 'High-Calorie Diet', 'Soft and bland foods', 'Oral rehydration solutions']::text[], ARRAY['Stay hydrated', 'Consume nutrient-rich foods', 'Include protein-rich foods', 'Consume foods rich in antioxidants', 'Limit fatty and greasy foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Chicken pox', 'chicken-pox', 'Chicken pox is a highly contagious viral infection causing an itchy rash.', ARRAY[]::text[], ARRAY['use neem in bathing ', 'consume neem leaves', 'take vaccine']::text[], ARRAY['Antiviral drugs', 'Pain relievers', 'IV fluids', 'Blood transfusions', 'Platelet transfusions']::text[], ARRAY['Chicken Pox Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Stay hydrated', 'Include easily digestible foods', 'Include vitamin C-rich foods', 'Consume protein-rich foods', 'Include zinc-rich foods', 'Avoid spicy and acidic foods', 'Consult a healthcare professional', 'Practice good hygiene', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Dengue', 'dengue', 'Dengue is a mosquito-borne viral infection causing flu-like symptoms.', ARRAY[]::text[], ARRAY['drink papaya leaf juice', 'avoid fatty spicy food', 'keep mosquitos away']::text[], ARRAY['Antibiotics', 'Antipyretics', 'Analgesics', 'IV fluids', 'Corticosteroids']::text[], ARRAY['Dengue Diet', 'Hydration', 'High-Calorie Diet', 'Soft and bland foods', 'Protein-rich foods']::text[], ARRAY['Stay hydrated', 'Include nutrient-rich foods', 'Consume foods rich in vitamin C and antioxidants', 'Limit fatty and greasy foods', 'Avoid caffeine and alcohol', 'Include soft and easily digestible foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet', 'Follow medical recommendations']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Typhoid', 'typhoid', 'Typhoid is a bacterial infection that can lead to a high fever and gastrointestinal symptoms.', ARRAY[]::text[], ARRAY['eat high calorie vegitables', 'antiboitic therapy', 'consult doctor']::text[], ARRAY['Vaccination', 'Antiviral drugs', 'IV fluids', 'Blood transfusions', 'Liver transplant']::text[], ARRAY['Typhoid Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Consume easily digestible foods', 'Stay hydrated', 'Include nutrient-rich foods', 'Consume foods rich in vitamin C and antioxidants', 'Include protein-rich foods', 'Avoid fatty and greasy foods', 'Consult a healthcare professional', 'Gradually resume normal diet', 'Follow medical recommendations', 'Avoid alcohol and caffeine']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('hepatitis A', 'hepatitis-a', 'hepatitis A is a viral liver disease.', ARRAY[]::text[], ARRAY['Consult nearest hospital', 'wash hands through', 'avoid fatty spicy food']::text[], ARRAY['Vaccination', 'Antiviral drugs', 'IV fluids', 'Blood transfusions', 'Liver transplant']::text[], ARRAY['Hepatitis A Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Stay hydrated', 'Consume nutrient-rich foods', 'Include protein-rich foods', 'Consume easily digestible foods', 'Limit fatty foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hepatitis B', 'hepatitis-b', 'Hepatitis B is a viral infection that attacks the liver.', ARRAY[]::text[], ARRAY['consult nearest hospital', 'vaccination', 'eat healthy']::text[], ARRAY['Antiviral drugs', 'IV fluids', 'Blood transfusions', 'Platelet transfusions', 'Liver transplant']::text[], ARRAY['Hepatitis B Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Follow a balanced and nutritious diet', 'Stay hydrated', 'Include protein-rich foods', 'Consume nutrient-rich foods', 'Limit fatty foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hepatitis C', 'hepatitis-c', 'Hepatitis C is a viral infection that causes liver inflammation.', ARRAY[]::text[], ARRAY['Consult nearest hospital', 'vaccination', 'eat healthy']::text[], ARRAY['Antiviral drugs', 'IV fluids', 'Blood transfusions', 'Platelet transfusions', 'Liver transplant']::text[], ARRAY['Hepatitis C Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Follow a balanced and nutritious diet', 'Stay hydrated', 'Include protein-rich foods', 'Consume nutrient-rich foods', 'Limit fatty foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hepatitis D', 'hepatitis-d', 'Hepatitis D is a serious liver disease caused by the hepatitis D virus.', ARRAY[]::text[], ARRAY['consult doctor', 'medication', 'eat healthy']::text[], ARRAY['Antiviral drugs', 'IV fluids', 'Blood transfusions', 'Platelet transfusions', 'Liver transplant']::text[], ARRAY['Hepatitis D Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Follow a balanced and nutritious diet', 'Stay hydrated', 'Include protein-rich foods', 'Consume nutrient-rich foods', 'Limit fatty foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hepatitis E', 'hepatitis-e', 'Hepatitis E is a viral infection that causes liver inflammation.', ARRAY[]::text[], ARRAY['stop alcohol consumption', 'rest', 'consult doctor']::text[], ARRAY['Alcohol cessation', 'Corticosteroids', 'IV fluids', 'Liver transplant', 'Nutritional support']::text[], ARRAY['Hepatitis E Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Stay hydrated', 'Consume nutrient-rich foods', 'Include protein-rich foods', 'Consume easily digestible foods', 'Limit fatty foods', 'Avoid alcohol and caffeine', 'Include vitamin C-rich foods', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Alcoholic hepatitis', 'alcoholic-hepatitis', 'Alcoholic hepatitis is inflammation of the liver due to alcohol consumption.', ARRAY[]::text[], ARRAY['stop alcohol consumption', 'consult doctor', 'medication']::text[], ARRAY['Antibiotics', 'Isoniazid', 'Rifampin', 'Ethambutol', 'Pyrazinamide']::text[], ARRAY['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']::text[], ARRAY['Avoid alcohol consumption', 'Follow a balanced and nutritious diet', 'Stay hydrated', 'Consume nutrient-rich foods', 'Include protein-rich foods', 'Limit fatty foods', 'Include antioxidants', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Tuberculosis', 'tuberculosis', 'Tuberculosis is a bacterial infection that primarily affects the lungs.', ARRAY[]::text[], ARRAY['cover mouth', 'consult doctor', 'medication']::text[], ARRAY['Antipyretics', 'Decongestants', 'Cough suppressants', 'Antihistamines', 'Pain relievers']::text[], ARRAY['TB Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Consume a high-protein diet', 'Include nutrient-rich foods', 'Stay hydrated', 'Consume foods rich in vitamins A and C', 'Include zinc-rich foods', 'Limit sugary foods and beverages', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet', 'Follow medical recommendations']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Common Cold', 'common-cold', 'Common Cold is a viral infection of the upper respiratory tract.', ARRAY[]::text[], ARRAY['drink vitamin c rich drinks', 'take vapour', 'avoid cold food']::text[], ARRAY['Antibiotics', 'Antiviral drugs', 'Antifungal drugs', 'IV fluids', 'Oxygen therapy']::text[], ARRAY['Cold Diet', 'Hydration', 'Warm fluids', 'Rest', 'Honey and lemon tea']::text[], ARRAY['Stay hydrated', 'Include nutrient-rich foods', 'Consume foods rich in vitamin C and antioxidants', 'Include zinc-rich foods', 'Limit sugary foods and beverages', 'Consume chicken soup', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet', 'Follow medical recommendations']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Pneumonia', 'pneumonia', 'Pneumonia is an inflammatory condition affecting the air sacs in the lungs.', ARRAY[]::text[], ARRAY['consult doctor', 'medication', 'rest']::text[], ARRAY['Laxatives', 'Pain relievers', 'Warm baths', 'Cold compresses', 'High-fiber diet']::text[], ARRAY['Pneumonia Diet', 'High-Calorie Diet', 'Soft and bland foods', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Stay hydrated', 'Include nutrient-rich foods', 'Consume foods rich in vitamin C and antioxidants', 'Include zinc-rich foods', 'Limit sugary foods and beverages', 'Consume chicken soup', 'Consult a healthcare professional', 'Rest and conserve energy', 'Gradually resume normal diet', 'Follow medical recommendations']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Dimorphic hemmorhoids(piles)', 'dimorphic-hemmorhoidspiles', 'Dimorphic hemmorhoids(piles) is a condition characterized by swollen blood vessels in the rectum.', ARRAY[]::text[], ARRAY['avoid fatty spicy food', 'consume witch hazel', 'warm bath with epsom salt']::text[], ARRAY['Nitroglycerin', 'Aspirin', 'Beta-blockers', 'Calcium channel blockers', 'Thrombolytic drugs']::text[], ARRAY['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydration', 'Warm baths', 'Stool softeners']::text[], ARRAY['Consume high-fiber foods', 'Stay hydrated', 'Include nutrient-rich foods', 'Consume foods rich in flavonoids', 'Limit processed foods', 'Avoid spicy and greasy foods', 'Consult a healthcare professional', 'Practice good hygiene', 'Gradually resume normal diet', 'Follow medical recommendations']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Heart attack', 'heart-attack', 'Heart attack is a sudden and severe reduction in blood flow to the heart muscle.', ARRAY[]::text[], ARRAY['call ambulance', 'chew or swallow asprin', 'keep calm']::text[], ARRAY['Compression stockings', 'Exercise', 'Elevating the legs', 'Sclerotherapy', 'Laser treatments']::text[], ARRAY['Heart-Healthy Diet', 'Low-sodium foods', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']::text[], ARRAY['Follow a heart-healthy diet', 'Limit sodium intake', 'Include fiber-rich foods', 'Consume healthy fats', 'Include lean proteins', 'Limit sugary foods and beverages', 'Stay hydrated', 'Consult a healthcare professional', 'Follow medical recommendations', 'Engage in regular exercise']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Varicose veins', 'varicose-veins', 'Varicose veins are enlarged, twisted veins that usually appear on the legs.', ARRAY[]::text[], ARRAY['lie down flat and raise the leg high', 'use oinments', 'use vein compression']::text[], ARRAY['Levothyroxine', 'Antithyroid medications', 'Beta-blockers', 'Radioactive iodine', 'Thyroid surgery']::text[], ARRAY['Varicose Veins Diet', 'High-Fiber Diet', 'Fruits and vegetables', 'Whole grains', 'Low-sodium foods']::text[], ARRAY['Consume a high-fiber diet', 'Stay hydrated', 'Include nutrient-rich foods', 'Consume foods rich in antioxidants', 'Limit sodium intake', 'Include flavonoid-rich foods', 'Avoid standing or sitting for long periods', 'Consult a healthcare professional', 'Follow medical recommendations', 'Engage in regular exercise']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hypothyroidism', 'hypothyroidism', 'Hypothyroidism is a condition where the thyroid gland doesn''t produce enough thyroid hormone.', ARRAY[]::text[], ARRAY['reduce stress', 'exercise', 'eat healthy']::text[], ARRAY['Antithyroid medications', 'Radioactive iodine', 'Thyroid surgery', 'Beta-blockers', 'Corticosteroids']::text[], ARRAY['Hypothyroidism Diet', 'Iodine-rich foods', 'Selenium-rich foods', 'Fruits and vegetables', 'Whole grains']::text[], ARRAY['Include iodine-rich foods', 'Consume selenium-rich foods', 'Stay hydrated', 'Include nutrient-rich foods', 'Limit processed foods', 'Consume foods rich in vitamins B and D', 'Consult a healthcare professional', 'Follow medical recommendations', 'Maintain a stable weight', 'Engage in regular exercise']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hyperthyroidism', 'hyperthyroidism', 'Hyperthyroidism is a condition where the thyroid gland produces too much thyroid hormone.', ARRAY[]::text[], ARRAY['eat healthy', 'massage', 'use lemon balm']::text[], ARRAY['Glucose tablets', 'Candy or juice', 'Glucagon injection', 'IV dextrose', 'Diazoxide']::text[], ARRAY['Hyperthyroidism Diet', 'Low-Iodine Diet', 'Calcium-rich foods', 'Selenium-rich foods', 'Fruits and vegetables']::text[], ARRAY['Limit iodine intake', 'Consume cruciferous vegetables in moderation', 'Stay hydrated', 'Include nutrient-rich foods', 'Limit caffeine and alcohol', 'Include omega-3 fatty acids', 'Consult a healthcare professional', 'Follow medical recommendations', 'Maintain a stable weight', 'Engage in regular exercise']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Hypoglycemia', 'hypoglycemia', 'Hypoglycemia is a condition characterized by abnormally low blood sugar levels.', ARRAY[]::text[], ARRAY['lie down on side', 'check in pulse', 'drink sugary drinks']::text[], ARRAY['Pain relievers', 'Exercise', 'Hot and cold packs', 'Joint protection', 'Physical therapy']::text[], ARRAY['Hypoglycemia Diet', 'Complex carbohydrates', 'Protein-rich snacks', 'Fiber-rich foods', 'Healthy fats']::text[], ARRAY['Consume complex carbohydrates', 'Include protein-rich foods', 'Stay hydrated', 'Limit sugary foods and beverages', 'Consume regular meals and snacks', 'Consult a healthcare professional', 'Monitor blood sugar levels', 'Follow medical recommendations', 'Engage in regular physical activity', 'Limit alcohol intake']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Osteoarthristis', 'osteoarthristis', 'Osteoarthristis is a degenerative joint disease that affects the cartilage in joints.', ARRAY[]::text[], ARRAY['acetaminophen', 'consult nearest hospital', 'follow up']::text[], ARRAY['NSAIDs', 'Disease-modifying antirheumatic drugs (DMARDs)', 'Biologics', 'Corticosteroids', 'Joint replacement surgery']::text[], ARRAY['Arthritis Diet', 'Anti-Inflammatory Diet', 'Omega-3-rich foods', 'Fruits and vegetables', 'Whole grains']::text[], ARRAY['Consume anti-inflammatory foods', 'Include omega-3 fatty acids', 'Consume antioxidant-rich foods', 'Stay hydrated', 'Limit processed foods', 'Include vitamin K-rich foods', 'Consult a healthcare professional', 'Follow medical recommendations', 'Engage in low-impact exercise', 'Maintain a healthy weight']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Arthritis', 'arthritis', 'Arthritis is inflammation of one or more joints, causing pain and stiffness.', ARRAY[]::text[], ARRAY['exercise', 'use hot and cold therapy', 'try acupuncture']::text[], ARRAY['Vestibular rehabilitation', 'Canalith repositioning', 'Medications for nausea', 'Surgery', 'Home exercises']::text[], ARRAY['Arthritis Diet', 'Anti-Inflammatory Diet', 'Omega-3-rich foods', 'Fruits and vegetables', 'Whole grains']::text[], ARRAY['Consume anti-inflammatory foods', 'Include omega-3 fatty acids', 'Consume antioxidant-rich foods', 'Stay hydrated', 'Limit processed foods', 'Include vitamin K-rich foods', 'Consult a healthcare professional', 'Follow medical recommendations', 'Engage in low-impact exercise', 'Maintain a healthy weight']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('(vertigo) Paroymsal Positional Vertigo', 'vertigo-paroymsal-positional-vertigo', '(Vertigo) Paroxysmal Positional Vertigo is a type of dizziness caused by specific head movements.', ARRAY[]::text[], ARRAY[]::text[], ARRAY['Topical treatments', 'Antibiotics', 'Oral medications', 'Hormonal treatments', 'Isotretinoin']::text[], ARRAY['Vertigo Diet', 'Low-Salt Diet', 'Hydration', 'Ginger tea', 'Vitamin D-rich foods']::text[], ARRAY[]::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Acne', 'acne', 'Acne is a skin condition that occurs when hair follicles become clogged with oil and dead skin cells.', ARRAY[]::text[], ARRAY['bath twice', 'avoid fatty spicy food', 'drink plenty of water']::text[], ARRAY['Antibiotics', 'Pain relievers', 'Antihistamines', 'Corticosteroids', 'Topical treatments']::text[], ARRAY['Acne Diet', 'Low-Glycemic Diet', 'Hydration', 'Fruits and vegetables', 'Probiotics']::text[], ARRAY['Consume a balanced diet', 'Limit dairy and high-glycemic foods', 'Include antioxidants', 'Stay hydrated', 'Limit processed foods', 'Include zinc-rich foods', 'Consult a skincare professional', 'Practice good skincare hygiene', 'Limit sugary foods and beverages', 'Follow medical recommendations']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Urinary tract infection', 'urinary-tract-infection', 'Urinary tract infection is an infection in any part of the urinary system.', ARRAY[]::text[], ARRAY['drink plenty of water', 'increase vitamin c intake', 'drink cranberry juice']::text[], ARRAY['Antibiotics', 'Urinary analgesics', 'Phenazopyridine', 'Antispasmodics', 'Probiotics']::text[], ARRAY['UTI Diet', 'Hydration', 'Cranberry juice', 'Probiotics', 'Vitamin C-rich foods']::text[], ARRAY['Stay hydrated', 'Consume cranberry products', 'Include vitamin C-rich foods', 'Limit caffeine and alcohol', 'Consume probiotics', 'Avoid spicy and acidic foods', 'Consult a healthcare professional', 'Follow medical recommendations', 'Maintain good hygiene', 'Limit sugary foods and beverages']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Psoriasis', 'psoriasis', 'Psoriasis is a chronic skin condition characterized by red, itchy, and scaly patches.', ARRAY[]::text[], ARRAY['wash hands with warm soapy water', 'stop bleeding using pressure', 'consult doctor']::text[], ARRAY['Topical treatments', 'Phototherapy', 'Systemic medications', 'Biologics', 'Coal tar']::text[], ARRAY['Psoriasis Diet', 'Anti-Inflammatory Diet', 'Omega-3-rich foods', 'Fruits and vegetables', 'Whole grains']::text[], ARRAY['Consume anti-inflammatory foods', 'Include omega-3 fatty acids', 'Include vitamin D analogues', 'Limit alcohol consumption', 'Stay hydrated', 'Consult a healthcare professional', 'Limit processed foods', 'Follow medical recommendations', 'Manage stress', 'Consider phototherapy under medical guidance']::text[], 'General Physician', 'moderate', 5, true);
INSERT INTO public.disease_library (name, slug, description, symptoms, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, severity, severity_score, is_active)
VALUES ('Impetigo', 'impetigo', 'Impetigo is a highly contagious skin infection causing red sores that can break open.', ARRAY[]::text[], ARRAY['soak affected area in warm water', 'use antibiotics', 'remove scabs with wet compressed cloth']::text[], ARRAY['Topical antibiotics', 'Oral antibiotics', 'Antiseptics', 'Ointments', 'Warm compresses']::text[], ARRAY['Impetigo Diet', 'Antibiotic treatment', 'Fruits and vegetables', 'Hydration', 'Protein-rich foods']::text[], ARRAY['Maintain good hygiene', 'Stay hydrated', 'Consume nutrient-rich foods', 'Limit sugary foods and beverages', 'Include foods rich in vitamin C', 'Consult a healthcare professional', 'Follow medical recommendations', 'Avoid scratching', 'Take prescribed antibiotics', 'Practice wound care']::text[], 'General Physician', 'moderate', 5, true);