#!/usr/bin/env python3
import csv
import json
import os
from pathlib import Path
import re

def slugify(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip('-')

ROOT = Path(__file__).resolve().parents[1]
TRAIN = ROOT / 'Training.csv'
DESC = ROOT / 'description.csv'
MEDS = ROOT / 'medications.csv'
DIETS = ROOT / 'diets.csv'
PRECAUTIONS = ROOT / 'precautions_df.csv'
WORKOUT = ROOT / 'workout_df.csv'

def read_csv_map(path, key_col='Disease', val_col=None):
    m = {}
    if not path.exists():
        return m
    with open(path, encoding='utf-8') as f:
        reader = csv.reader(f)
        headers = next(reader)
        # If two columns: Disease, Value
        for row in reader:
            if not row:
                continue
            k = row[0].strip()
            v = row[1].strip() if len(row)>1 else ''
            m[k] = v
    return m

def load_training_symptoms():
    with open(TRAIN, encoding='utf-8') as f:
        reader = csv.DictReader(f)
        symptom_cols = [c for c in reader.fieldnames if c!='prognosis']
        disease_sym = {}
        for row in reader:
            prog = row['prognosis'].strip()
            disease_sym.setdefault(prog, {})
            for s in symptom_cols:
                if row[s].strip()=='1':
                    disease_sym[prog][s]=disease_sym[prog].get(s,0)+1
    # Convert counts to sorted list
    out = {}
    for d,counts in disease_sym.items():
        # top 8 symptoms
        top = sorted(counts.items(), key=lambda x:-x[1])[:8]
        out[d]=[s for s,_ in top]
    return out

def parse_list_string(s):
    # CSV has strings like "['A','B']"
    try:
        return json.loads(s.replace("'","\""))
    except Exception:
        return [x.strip() for x in s.split(',') if x.strip()]

def load_list_map(path):
    m={}
    if not path.exists():
        return m
    with open(path,encoding='utf-8') as f:
        reader=csv.reader(f)
        next(reader)
        for row in reader:
            if not row: continue
            k=row[0].strip()
            v=row[1].strip() if len(row)>1 else ''
            m[k]=parse_list_string(v)
    return m

def main():
    Path('scripts').mkdir(exist_ok=True)
    desc_map = read_csv_map(DESC)
    meds_map = load_list_map(MEDS)
    diets_map = load_list_map(DIETS)
    prec_map = load_list_map(PRECAUTIONS)
    work_map = load_list_map(WORKOUT)
    sym_map = load_training_symptoms()

    diseases = list(sym_map.keys())

    target = 200
    placeholders_needed = max(0, target - len(diseases))

    out_sql = []
    out_sql.append('-- Seed disease_library: generated by scripts/generate_disease_seed.py')
    out_sql.append('BEGIN;')
    for d in diseases:
        name = d
        slug = slugify(name)
        description = desc_map.get(name, f'{name} — Description pending.')
        symptoms = sym_map.get(name, [])
        meds = meds_map.get(name, [])
        diets = diets_map.get(name, [])
        prec = prec_map.get(name, [])
        workout = work_map.get(name, [])
        specialist = 'General Physician'
        severity_score = max(3.0, min(9.0, float(len(symptoms))))
        severity = 'moderate'
        body_system = 'general'

        # build SQL
        vals = (
            "uuid_generate_v4()",
            name.replace("'","''"),
            slug,
            description.replace("'","''"),
            '{' + ','.join([s.replace('}',']').replace('{','') for s in symptoms]) + '}',
            str(severity_score),
            severity,
            '{' + ','.join([p.replace("'","''") for p in prec]) + '}',
            '{' + ','.join([m.replace("'","''") for m in meds]) + '}',
            '{' + ','.join([d.replace("'","''") for d in diets]) + '}',
            '{' + ','.join([w.replace("'","''") for w in workout]) + '}',
            specialist,
            body_system,
            'true'
        )
        insert_stmt = (
            "INSERT INTO public.disease_library (id, name, slug, description, symptoms, severity_score, severity, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, body_system, is_active) VALUES ("
            + ", ".join([f"'{v}'" if not v.startswith('uuid_generate') and v not in ['true','false'] else v for v in vals]) + ");"
        )
        out_sql.append(insert_stmt)

    if placeholders_needed>0:
        out_sql.append(f"-- Insert {placeholders_needed} placeholder diseases")
        out_sql.append("INSERT INTO public.disease_library (id, name, slug, description, symptoms, severity_score, severity, precautions, medications, diet_recommendations, workout_recommendations, specialist_type, body_system, is_active)")
        out_sql.append(f"SELECT uuid_generate_v4(), 'Placeholder Disease ' || gs, 'placeholder-disease-' || gs, 'Placeholder description for review.', ARRAY[]::text[], 5.0, 'mild', ARRAY['consult doctor']::text[], ARRAY['medication']::text[], ARRAY['balanced diet']::text[], ARRAY['light exercise']::text[], 'General Physician', 'general', true FROM generate_series(1,{placeholders_needed}) AS gs;")

    out_sql.append('COMMIT;')
    sql_path = Path('scripts/seed_disease_library.sql')
    with open(sql_path,'w',encoding='utf-8') as f:
        f.write('\n'.join(out_sql))
    print(f'Wrote {sql_path}')

    # Also produce a JSON payload for API seeding and frontend mocking
    json_out = []
    for d in diseases:
        name = d
        slug = slugify(name)
        description = desc_map.get(name, f'{name} — Description pending.')
        symptoms = sym_map.get(name, [])
        meds = meds_map.get(name, [])
        diets = diets_map.get(name, [])
        prec = prec_map.get(name, [])
        workout = work_map.get(name, [])
        specialist = 'General Physician'
        severity_score = max(3.0, min(9.0, float(len(symptoms))))
        severity = 'moderate'
        body_system = 'general'

        json_out.append({
            'name': name,
            'slug': slug,
            'description': description,
            'symptoms': symptoms,
            'severity_score': severity_score,
            'severity': severity,
            'precautions': prec,
            'medications': meds,
            'diet_recommendations': diets,
            'workout_recommendations': workout,
            'specialist_type': specialist,
            'body_system': body_system,
            'is_active': True
        })

    # Add placeholders as simple objects
    for i in range(1, placeholders_needed+1):
        json_out.append({
            'name': f'Placeholder Disease {i}',
            'slug': f'placeholder-disease-{i}',
            'description': 'Placeholder description for review.',
            'symptoms': [],
            'severity_score': 5.0,
            'severity': 'mild',
            'precautions': ['consult doctor'],
            'medications': ['medication'],
            'diet_recommendations': ['balanced diet'],
            'workout_recommendations': ['light exercise'],
            'specialist_type': 'General Physician',
            'body_system': 'general',
            'is_active': True
        })

    json_path = Path('scripts/disease_library.json')
    with open(json_path,'w',encoding='utf-8') as f:
        json.dump(json_out, f, indent=2, ensure_ascii=False)
    print(f'Wrote {json_path}')

    # Also write a copy for frontend mock data
    frontend_path = ROOT / 'frontend' / 'src' / 'data'
    frontend_path.mkdir(parents=True, exist_ok=True)
    frontend_json_path = frontend_path / 'expandedDiseaseLibrary.json'
    with open(frontend_json_path,'w',encoding='utf-8') as f:
        json.dump(json_out, f, indent=2, ensure_ascii=False)
    print(f'Wrote {frontend_json_path}')

if __name__=='__main__':
    main()
